# Generated by Django 5.2.16 on 2026-08-08 16:29

import apps.app_download.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Download category',
                'verbose_name_plural': 'Download categories',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DownloadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(storage=apps.app_download.storage.get_cdn_storage, upload_to='downloads/%Y/%m/')),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
                ('password_hash', models.CharField(blank=True, max_length=128)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='app_download.downloadcategory')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_download_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Download file',
                'verbose_name_plural': 'Download files',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DownloadReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=120)),
                ('details', models.TextField(blank=True)),
                ('reporter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app_download.downloadfile')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Download report',
                'verbose_name_plural': 'Download reports',
                'ordering': ('-created_at',),
            },
        ),
    ]
