# Generated by Django 5.2.16 on 2026-07-27 18:02

import apps.app_account.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('about', 'درباره ما'), ('contact', 'تماس با ما')], max_length=20, verbose_name='صفحه')),
                ('key', models.CharField(max_length=100, verbose_name='کلید')),
                ('value', models.TextField(verbose_name='مقدار')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون (اختیاری)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'محتوای سایت',
                'verbose_name_plural': 'محتوای سایت',
                'ordering': ['page', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=apps.app_account.models.profile_picture_upload_to, verbose_name='تصویر پروفایل')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='کد ملی')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('mac_address', models.CharField(blank=True, max_length=32, verbose_name='آدرس MAC')),
                ('mac_source', models.CharField(blank=True, choices=[('ip', 'IP'), ('hdd', 'HDD'), ('generated', 'تولیدشده')], max_length=16, verbose_name='منبع MAC')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='تعداد کلیک\u200cها')),
                ('login_attempt_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تلاش\u200cهای ورود')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_tried', models.CharField(max_length=150, verbose_name='نام کاربری تلاش\u200cشده')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('successful', models.BooleanField(default=False, verbose_name='موفق')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تلاش ورود',
                'verbose_name_plural': 'تلاش\u200cهای ورود',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserScanSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('1h', 'هر ۱ ساعت'), ('3h', 'هر ۳ ساعت'), ('6h', 'هر ۶ ساعت'), ('1d', 'هر روز')], default='1h', max_length=8, verbose_name='بازه به\u200cروزرسانی')),
                ('last_scan_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین اسکن')),
                ('scan_version', models.PositiveIntegerField(default=0, verbose_name='نسخه اسکن')),
                ('last_fingerprint', models.CharField(blank=True, max_length=64, verbose_name='اثرانگشت پوشه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_setting', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تنظیمات اسکن',
                'verbose_name_plural': 'تنظیمات اسکن',
            },
        ),
    ]
