# Generated by Django 6.0.6 on 2026-07-28 12:42

import apps.app_account.models
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0002_phone_national_id_limits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='click count'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_attempt_count',
            field=models.PositiveIntegerField(default=0, verbose_name='login attempt count'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mac_address',
            field=models.CharField(blank=True, max_length=32, verbose_name='MAC address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mac_source',
            field=models.CharField(blank=True, choices=[('ip', 'IP'), ('hdd', 'HDD'), ('generated', 'تولیدشده')], max_length=16, verbose_name='MAC source'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='national ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.app_account.models.profile_picture_upload_to, verbose_name='profile picture'),
        ),
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_acc_username', models.CharField(max_length=150, unique=True, verbose_name='شماره حساب')),
                ('broker', models.CharField(max_length=200, verbose_name='نام کارگزاری')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
                ('users', models.ManyToManyField(blank=True, related_name='trading_accounts', to=settings.AUTH_USER_MODEL, verbose_name='کاربران')),
            ],
            options={
                'verbose_name': 'حساب ترید',
                'verbose_name_plural': 'حساب\u200cهای ترید',
                'ordering': ['trading_acc_username'],
            },
        ),
        migrations.DeleteModel(
            name='UserScanSetting',
        ),
    ]
