# Generated by Django 6.0.6 on 2026-07-28 13:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0003_trading_account_remove_scan_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='درباره ما', max_length=200, verbose_name='عنوان')),
                ('body', models.TextField(blank=True, help_text='محتوای HTML با TinyMCE', verbose_name='محتوا')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'صفحه درباره ما',
                'verbose_name_plural': 'صفحه درباره ما',
            },
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='page',
            field=models.CharField(choices=[('about', 'درباره ما'), ('contact', 'تماس با ما'), ('faq', 'سؤالات متداول')], max_length=20, verbose_name='صفحه'),
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_label', models.CharField(default='anonymous', help_text='نام کاربری یا anonymous', max_length=150, verbose_name='برچسب بازدیدکننده')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('mac_address', models.CharField(blank=True, max_length=32, verbose_name='آدرس MAC')),
                ('path', models.CharField(max_length=500, verbose_name='مسیر')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_visits', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بازدید صفحه',
                'verbose_name_plural': 'بازدیدهای صفحه',
                'ordering': ['-created_at'],
            },
        ),
    ]
