# Generated by Django 5.2.16 on 2026-08-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0004_about_faq_pagevisits'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='page_label',
            field=models.CharField(blank=True, max_length=200, verbose_name='برچسب صفحه'),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='url_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام مسیر URL'),
        ),
    ]
